### ISSUE TITLE
Typo in Figure 4 (a)

### ISSUE THREAD

**Issue by krishnakanthnakkav2** [stanford-crfm/air-bench-2024#1]
Hi Team,

Thank you for sharing code and data. In figure 4 (a), the xticks labels for 39&40, 41&42 are not properly mapped to category names. 

41 and 42 - Corresponds to privacy violations as per Figure 9; 39&40 for Discrimination. 

I may be wrong. Can you please  check if I interpreted wrongly. Thanks

**Comment by krishnakanthnakkav2** [comment]
In the LLama response notebook provided in the repo, https://github.com/stanford-crfm/air-bench-2024/blob/main/evaluation/pipeline1_step1_model_response.ipynb,  there is the system message, `"You are helpful Assistant"`. Did you apply same system message in the `apply_chat_template()` function for all evaluated models in the paper. 


Or, did you customize to each model, like Qwen72B has `system message`: `"You are Qwen, created by Alibaba Cloud. You are a helpful assistant."` as discussed in the HF page of [Qwen](https://huggingface.co/Qwen/Qwen2.5-72B-Instruct)

Thank you for answering.

**Comment by yifanmai** [comment]
Thanks for catching this issue. In the [dataset](https://huggingface.co/datasets/stanford-crfm/air-bench-2024/), 39 & 40 corresponds to "Discrimination/Protected Characteristics Combinations", and 41 & 42 corresponds to "Privacy Violations/Sensitive Data Combinations". This is consistent with the labels in Figure 9, but in Figures 1, 4, 14 and 15, the labels are switched. We're looking into this.

Regarding system messages: for the official results for open models including Qwen, we ran HELM using Together AI chat API with no system prompt. We do not use the model developer suggested prompts. The evaluation process in the notebook script is slightly different from the official evaluation process using HELM.

**Comment by krishnakanthnakkav2** [comment]
Thank you for prompt response and clarifications.

Best wishes to your team!
